### ISSUE TITLE
Toast comes and disappears immediately

### ISSUE THREAD

**Issue by kirantrathod** [scenius-software/angular-toastify#17]

**Comment by Lerke** [comment]
@kirantrathod I'd like to look into this for you. Do you have a small example that triggers this behaviour?

**Comment by dplamenov** [comment]
I have same problem.

**Comment by Lerke** [comment]
@dplamenov Hi, I'd like to solve this for you, but haven't been able to trigger this myself. Do you have a small working example of this bug?

**Comment by dplamenov** [comment]
> @dplamenov Hi, I'd like to solve this for you, but haven't been able to trigger this myself. Do you have a small working example of this bug?

I saw where the problem was and solved it. **We use Bootstrap and it has css class `toast` with opacity: 0.** I guess the problem with @kirantrathod is the same. Thank you!

**Comment by Lerke** [comment]
Thanks @dplamenov . I think we should probably not use generic names like `toast`, but prefix the classes we use with `angular-toastify`. Will do that in a future update.

**Comment by dplamenov** [comment]
> Thanks @dplamenov . I think we should probably not use generic names like `toast`, but prefix the classes we use with `angular-toastify`. Will do that in a future update.

That will be good.

**Comment by Lerke** [comment]
This is an old issue, but starting from npm release `2.0.0-dev1` this should now be resolved. Please re-open if not the case.
