### ISSUE TITLE
Angular Ivy Compatibility?

### ISSUE THREAD

**Issue by alvissraghnall** [scenius-software/angular-toastify#49]
After importing the module in some module of my application, it throws an error:

```
AngularToastifyModule is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.
```

I was able to fix it by setting aot: false in angular.json, but is there some other fix for this other than that?

**Comment by Lerke** [comment]
@alvissraghnall I'll look into this for you. If Toastify isn't Ivy compatible, then it should become so, for sure.

**Comment by Lerke** [comment]
Hi @alvissraghnall. I've tried replicating your issue, but I seem to be able to create a Angular 15 project with angular-toastify 1.0.5 nwithout any troubles (using just one AppModule). Do you have some information for me regarding your app (e.g. which versions are you using) and build process?

**Comment by Lerke** [comment]
Hi @alvissraghnall, @DanielMigchels pushed a new version 1.0.6 to our npm repository that should fix the error you encountered.
