### ISSUE TITLE
Coudn't use in a submodule

### ISSUE THREAD

**Issue by saaimbiz** [scenius-software/angular-toastify#9]
Works in app module but not in sub-module. Throwing following error, "BrowserModule has already been loaded"

**Comment by Lerke** [comment]
Hi, thanks for the issue. I was able to reproduce the problem. I've published version 1.0.4, could you check if that works for you? 

I've updated the demo pages to also have a (lazy) submodule:

- https://scenius-software.github.io/angular-toastify/
- https://scenius-software.github.io/angular-toastify/submodule

**Comment by Lerke** [comment]
Since above is more than a year old, I will assume the fix worked ;)
